---
#Плагин до модифицырывал opkiler22789 если будут сбои пишем --> http://infomcpe.ru/threads/chatgame.1485/
#Время minecraft промижуток между постами
time: 3600
#Минимум который возможно получить
min: 100 
#Максимум который возможно получить
max: 1000
#Включить/выключить выдачу предметов вместо денег
item: false
...
